### ISSUE TITLE
Ruby error when running.

### ISSUE THREAD

**Issue by bradleyg** [CenturyLinkLabs/fig2coreos#2]
`$ fig2coreos myapp fig.yml coreos-files`

``` shell
/Library/Ruby/Gems/2.0.0/gems/fig2coreos-0.1.4/lib/fig2coreos.rb:83:in `block (2 levels) in create_service_files': undefined method `first' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/fig2coreos-0.1.4/lib/fig2coreos.rb:76:in `open'
    from /Library/Ruby/Gems/2.0.0/gems/fig2coreos-0.1.4/lib/fig2coreos.rb:76:in `block in create_service_files'
    from /Library/Ruby/Gems/2.0.0/gems/fig2coreos-0.1.4/lib/fig2coreos.rb:34:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/fig2coreos-0.1.4/lib/fig2coreos.rb:34:in `create_service_files'
    from /Library/Ruby/Gems/2.0.0/gems/fig2coreos-0.1.4/lib/fig2coreos.rb:29:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/fig2coreos-0.1.4/lib/fig2coreos.rb:9:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/fig2coreos-0.1.4/lib/fig2coreos.rb:9:in `convert'
    from /Library/Ruby/Gems/2.0.0/gems/fig2coreos-0.1.4/bin/fig2coreos:47:in `<top (required)>'
    from /usr/bin/fig2coreos:23:in `load'
    from /usr/bin/fig2coreos:23:in `<main>'
```

And my fig file:

``` yaml
web:
  build: .
  volumes:
    - .:/code
  links:
   - db
   - redis
  ports:
   - 5000:5000
  command: python manage.py runserver 0.0.0.0:5000 --traceback
  environment:
    DJANGO_SETTINGS_MODULE: 'app.settings.local'

db:
  image: orchardup/postgresql

redis:
  image: orchardup/redis
```

Any ideas?
