### ISSUE TITLE
command in fig to command in docker run

### ISSUE THREAD

**Issue by montells** [CenturyLinkLabs/fig2coreos#3]
with the following fragment in fig yml

```
railsappdevelopment:
  image: myregistry:5000/railsapp
  ports:
    - "3000:3000"
  command: -e development
```

should generate following systemd:

```
[Unit]
Description=Run railsappdevelopment_1
After=docker.service
Requires=docker.service

[Service]
Restart=always
RestartSec=10s
ExecStartPre=/usr/bin/docker ps -a -q | xargs docker rm
ExecStart=/usr/bin/docker run -rm -name railsappdevelopment_1 -p 3000:3000    myregistry:5000/railsapp -e development
ExecStartPost=/usr/bin/docker ps -a -q | xargs docker rm
ExecStop=/usr/bin/docker kill railsappdevelopment_1
ExecStopPost=/usr/bin/docker ps -a -q | xargs docker rm

[Install]
WantedBy=local.target
```

In others words should add command in fig.yml to docker run call in ExecStart like a run command
